### PR TITLE
Netpyne

### PR DESCRIPTION
**Pull request by pgleeson**
Part of https://github.com/OpenSourceBrain/geppetto-osb/issues/49

### CODE REVIEW

**Comment by tarelli** [comment]
@pgleeson btw the instructions and the problem are not correlated, I think I have the dependencies installed locally (I took them from travis) but it would be good to be explicit in what they are in the README. Any idea why the test would hang like that?

**Comment by tarelli** [comment]
@pgleeson nevermind the test passed after restarting Eclipse, something was not being picked up. So just the README update :)

**Comment by pgleeson** [comment]
In short you need the latest version of libNeuroML and pyNeuroML. These should be pip installable (get very latest with `pip install libneuroml --update`). All in .travis.yml, but will make explicit in the README...

**Comment by pgleeson** [comment]
See https://github.com/openworm/org.geppetto.simulator.external/commit/24fe8d63edbd4ce220ba866ab33feffd5151979e

**Comment by tarelli** [comment]
@pgleeson Thanks!

**Comment by tarelli** [comment]
@pgleeson great stuff Padraig, glad to see all the tests added :) 💯

**Pull request merged**
